name: Terraform Lint

on:
  push:
    paths:
      - '**.tf'
      - 'input/*'
      - 'cloudinit/*'
      - '.github/workflows/terraform-lint.yml'
  pull_request:
    paths:
      - '**.tf'
      - 'input/*'
      - 'cloudinit/*'
      - '.github/workflows/terraform-lint.yml'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate SSH keypair
        run: |
          mkdir ~/.ssh
          ssh-keygen -t rsa -b 4096 -N "" -f ~/.ssh/id_rsa

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.1

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - uses: terraform-linters/setup-tflint@v4
        name: Setup TFLint
        with:
          tflint_version: latest
  
      - name: Init TFLint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}
  
      - name: Run TFLint
        run: tflint -f compact
