name: Terraform Lint

on:
  push:
    paths:
      - '**.tf'
      - 'input/'
      - 'cloudinit/'
      - '.github/workflows/'
  pull_request:
    paths:
      - '**.tf'
      - 'input/'
      - 'cloudinit/'
      - '.github/workflows/'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate SSH keypair
        run: |
          mkdir ~/.ssh
          ssh-keygen -t rsa -b 4096 -N "" -f ~/.ssh/id_rsa

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.1

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: Install TFLint
        run: curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
